---
kind: pipeline
type: docker
name: ci

platform:
  os: linux
  arch: amd64

steps:
- name: lint
  image: grafana/jsonnet-build:7f1cb84
  commands:
  - make lint

trigger:
  branch:
  - master
  event:
  - push
  - pull_request

---
kind: signature
hmac: d6c05915444d8389944b22da34f14b8f39abaaf18d52237a1f07cf7c5c42fc5b

...
